### PR TITLE
Correct shutdown and exit handling

### LINKED ISSUE #142: regression: invalid shutdown handler
- open vscode-sourcegraph extension project in VS code
- start debug session
- do a hover
- close 'Extension Development Host' window (it sends `shutdown`)

-> 
```
Unhandled exception has occurred: Error
Error: The received response has neither a result nor an error property.
    at handleInvalidMessage (c:\projects\vscode-sourcegraph\node_modules\vscode-jsonrpc\lib\main.js:294:40)
    at StreamMessageReader.callback (c:\projects\vscode-sourcegraph\node_modules\vscode-jsonrpc\lib\main.js:366:13)
    at StreamMessageReader.onData (c:\projects\vscode-sourcegraph\node_modules\vscode-jsonrpc\lib\messageReader.js:197:18)
```

### PR DESCRIPTION
**Pull request by alexsaveliev**
Closes #142 

- ~~added noop `exit` handler~~ ignore `exit`
- adjusted `shutdown` handler signature

### CODE REVIEW

File: src/typescript-service.ts [hunk 1]
```diff
@@ -143,8 +143,13 @@ export class TypeScriptService {
 		this.inMemoryFileSystem = new pm.InMemoryFileSystem(this.root);
 	}
 
-	async shutdown(params = {}, span = new Span()): Promise<void> {
+	async shutdown(params = {}, span = new Span()): Promise<null> {
 		this.projectManager.dispose();
+		return null;
+	}
+
+	async exit(params = {}, span = new Span()): Promise<void> {
```
Comment (felixfbecker) [inline src/typescript-service.ts]: I would like `exit` to be handled by the part that registers the handler, because that needs to kill the process or close the socket. I would ignore `exit` in `registerLanguageHandler`

File: src/typescript-service.ts [hunk 2]
```diff
@@ -143,8 +143,13 @@ export class TypeScriptService {
 		this.inMemoryFileSystem = new pm.InMemoryFileSystem(this.root);
 	}
 
-	async shutdown(params = {}, span = new Span()): Promise<void> {
+	async shutdown(params = {}, span = new Span()): Promise<null> {
 		this.projectManager.dispose();
+		return null;
```
Comment (felixfbecker) [inline src/typescript-service.ts]: Good catch. We should only let notification handlers return `void`, and request handlers always `null` if they don't have a result.
